import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const check = process.argv.includes("--check");
const source = check
  ? "catalog/model-catalog.v2.json"
  : "../../router/backend/catalog/model-catalog.v2.json";
const bytes = await readFile(source, "utf8");
const catalog = JSON.parse(bytes);
const sort = (value: unknown): unknown =>
  Array.isArray(value)
    ? value.map(sort)
    : value && typeof value === "object"
      ? Object.fromEntries(
          Object.entries(value)
            .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
            .map(([k, v]) => [k, sort(v)]),
        )
      : value;
const digest = `sha256:${createHash("sha256")
  .update(JSON.stringify(sort({ schema_version: catalog.schema_version, models: catalog.models })))
  .digest("hex")}`;
if (
  catalog.schema_version !== 2 ||
  digest !== catalog.catalog_digest ||
  !Array.isArray(catalog.models)
)
  throw new Error("Invalid canonical catalog");
const rawGenerated = `// Generated by scripts/sync-model-catalog.ts. Do not edit.\nexport type AdRouterThinkingLevel = "none" | "medium" | "high";\nexport const ADROUTER_CATALOG_DIGEST = ${JSON.stringify(digest)};\nexport const ADROUTER_CATALOG = ${JSON.stringify(catalog.models, null, 2)} as const;\nexport const ADROUTER_CODING_MODELS = ADROUTER_CATALOG.filter(model => model.id !== "kimi-k3" && model.tool_calling).map(model => ({id:model.id,name:model.display_name,thinkingLevels:model.thinking_levels as readonly AdRouterThinkingLevel[],defaultThinkingLevel:model.default_thinking_level,contextWindow:model.context_window,maxInputTokens:model.max_input_tokens,maxOutputTokens:model.max_output_tokens}));\nexport function defaultThinkingLevel(modelId:string):AdRouterThinkingLevel { return ADROUTER_CATALOG.find(model => model.id === modelId)?.default_thinking_level ?? "medium"; }\n`;
const formatted = spawnSync(
  "node_modules/.bin/biome",
  ["format", "--stdin-file-path=src/catalog.ts"],
  { input: rawGenerated, encoding: "utf8" },
);
if (formatted.status !== 0) throw new Error("Catalog formatting failed");
const generated = formatted.stdout;
if (check) {
  if ((await readFile("src/catalog.ts", "utf8")) !== generated)
    throw new Error("Generated catalog is stale");
} else {
  await mkdir("catalog", { recursive: true });
  const formattedJson = spawnSync(
    "node_modules/.bin/biome",
    ["format", "--stdin-file-path=catalog/model-catalog.v2.json"],
    { input: bytes, encoding: "utf8" },
  );
  if (formattedJson.status !== 0) throw new Error("Catalog JSON formatting failed");
  await writeFile("catalog/model-catalog.v2.json", formattedJson.stdout);
  await writeFile("src/catalog.ts", generated);
}
console.log(`Verified canonical catalog ${digest}`);
